name: Test

on:
   - push
   - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: make test
  release:
    name: release
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g @semantic-release/changelog @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator semantic-release
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

