name: Test

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: golang:1.18
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: make test
